apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: dkimisima/gitopsfc
  newTag: 6d3bad6504202fef53bbf78ad068ec03a35e109c
